(()=>{const tools=window.ATLAS_TOOLS||[],q=s=>document.querySelector(s),grid=q("#toolGrid"),quick=q("#quickGrid"),search=q("#searchInput"),filters=q("#filters"),empty=q("#emptyState");let view="home",cat="Alles";
const card=t=>{const live=!!t.url,ext=t.type==="Extern",label=t.status==="soon"?"In ontwikkeling":t.type;return `<${live?"a":"article"} class="card ${live?"":"disabled"}" ${live?`href="${t.url}" ${ext?'target="_blank" rel="noopener noreferrer"':""}`:""}><div class="cardtop"><span class="toolicon">${t.icon}</span><span class="badge ${t.type==="ATLAS"?"atlas":""}">${label}</span></div><h3>${t.title}</h3><p>${t.desc}</p><div class="meta"><span>${t.section}</span><span>·</span><span>${t.category}</span>${ext?"<b>↗</b>":""}</div></${live?"a":"article"}>`};
function cats(list){return ["Alles",...new Set(list.map(x=>x.category))]}
function render(){let base=view==="home"?tools:tools.filter(t=>t.section===view),term=search.value.trim().toLowerCase();let list=base.filter(t=>(cat==="Alles"||t.category===cat)&&(!term||[t.title,t.desc,t.category,t.section,...t.tags].join(" ").toLowerCase().includes(term)));filters.innerHTML=cats(base).map(c=>`<button class="chip ${c===cat?"active":""}" data-cat="${c}">${c}</button>`).join("");grid.innerHTML=list.map(card).join("");empty.hidden=!!list.length;q("#resultCount").textContent=`${list.length} ${list.length===1?"item":"items"}`;q("#quickSection").hidden=view!=="home"||!!term;q("#collectionLabel").textContent=view==="home"?"Toolbox":view;q("#collectionTitle").textContent=view==="home"?"Alles in ATLAS":view;const copy={home:["Goedenavond 👋","Alles wat je voor je les nodig hebt, zonder twaalf tabbladen open te hebben."],"Bordtools":["Bordtools","Snelle hulpmiddelen voor instructie, routines en klassenmanagement."],"Les-tools":["Les-tools","Slimme hulpmiddelen om sneller lesmateriaal en activiteiten klaar te zetten."],"Bronnen":["Bronnen","Handige externe tools die een vaste plek in je gereedschapskist verdienen."]}[view];q("#pageTitle").textContent=copy[0];q("#pageIntro").textContent=copy[1];}
function setView(v){view=v;cat="Alles";document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===v));document.body.classList.remove("menu-open");render()}
quick.innerHTML=tools.filter(t=>t.section==="Bordtools").slice(0,4).map(card).join("");q("#mainNav").addEventListener("click",e=>{let b=e.target.closest("[data-view]");if(b)setView(b.dataset.view)});document.addEventListener("click",e=>{let b=e.target.closest("[data-view-jump]");if(b)setView(b.dataset.viewJump)});filters.addEventListener("click",e=>{let b=e.target.closest("[data-cat]");if(b){cat=b.dataset.cat;render()}});search.addEventListener("input",render);document.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement!==search){e.preventDefault();search.focus()}});q("#menuButton").onclick=()=>document.body.classList.toggle("menu-open");
let deferred;const install=q("#installButton");window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;install.hidden=false});install.onclick=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;install.hidden=true};// Development: keep ATLAS fast and deterministic. Remove old PWA workers/caches.
if("serviceWorker" in navigator){
  navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{});
}
if("caches" in window){
  caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith("atlas-")).map(k=>caches.delete(k)))).catch(()=>{});
}
render()})();