window.ATLAS_TOOLS=[
{id:"timer",title:"Klassentimer",desc:"Een rustige, grote timer voor op het digibord.",icon:"⏱️",section:"Bordtools",category:"Tijd",type:"ATLAS",tags:["timer","tijd","digibord"],url:"board/",featured:true},
{id:"noise",title:"Geluidswereld",desc:"Laat een wereld groeien zolang de klas rustig werkt.",icon:"🌳",section:"Bordtools",category:"Klassenmanagement",type:"ATLAS",tags:["geluid","microfoon","stil","klas"],status:"soon",featured:true},
{id:"groups",title:"Groepjesmaker",desc:"Maak razendsnel willekeurige groepjes of duo's.",icon:"👥",section:"Bordtools",category:"Klassenmanagement",type:"ATLAS",tags:["groepjes","duo","random"],url:"tools/groups/",featured:true},
{id:"wheel",title:"Draaiwiel",desc:"Kies willekeurig een naam, opdracht of antwoord.",icon:"🎡",section:"Bordtools",category:"Kiezen",type:"ATLAS",tags:["rad","random","naam"],url:"tools/wheel/",featured:true},
{id:"traffic",title:"Stoplicht",desc:"Visuele afspraak voor zelfstandig werken en overleggen.",icon:"🚦",section:"Bordtools",category:"Klassenmanagement",type:"ATLAS",tags:["stoplicht","werken","stil"],url:"tools/traffic/"},
{id:"dice",title:"Dobbelstenen",desc:"Digitale dobbelstenen voor spel en instructie.",icon:"🎲",section:"Bordtools",category:"Kiezen",type:"ATLAS",tags:["dobbelsteen","spel"],url:"tools/dice/"},
{id:"worksheet",title:"Werkbladmaker",desc:"Maak printklare rekenwerkbladen en antwoordenbladen.",icon:"📄",section:"Les-tools",category:"Rekenen",type:"ATLAS",tags:["werkblad","rekenen","printen"],url:"tools/worksheet/",featured:true},
{id:"edi",title:"EDI-les",desc:"Bereid een expliciete directe instructieles voor met het ATLAS EDI-template.",icon:"🧭",section:"Les-tools",category:"Lesvoorbereiding",type:"ATLAS",tags:["edi","instructie","lesdoel","template"],url:"templates/edi/",featured:true},
{id:"contexts",title:"Contextsommen",desc:"Maak gerichte verhaalsommen passend bij groep en niveau.",icon:"🧠",section:"Les-tools",category:"Rekenen",type:"ATLAS",tags:["rekenen","contextsommen","verhaalsommen"],url:"tools/contexts/",featured:true},
{id:"dictation",title:"Dictee-tool",desc:"Bouw snel een dictee of oefenlijst voor spelling.",icon:"✏️",section:"Les-tools",category:"Spelling",type:"ATLAS",tags:["spelling","dictee","woorden"],status:"soon"},
{id:"quiz",title:"Quizmaker",desc:"Zet snel klassikale vragen klaar voor je les.",icon:"🎓",section:"Les-tools",category:"Quiz",type:"ATLAS",tags:["quiz","vragen","kennis"],status:"soon"},
{id:"shysafari",title:"Shy Safari",desc:"Externe geluidsmeter waarbij dieren verschijnen als de klas rustig blijft.",icon:"🦒",section:"Bronnen",category:"Klassenmanagement",type:"Extern",tags:["geluid","rust","microfoon"],url:"https://shysafari.com"},
{id:"teacherdev",title:"Teacher.dev",desc:"Verzameling creatieve, gratis webtools voor leerkrachten.",icon:"🧰",section:"Bronnen",category:"Toolbox",type:"Extern",tags:["tools","teacher","digibord"],url:"https://teacher.dev"}
];