(()=>{const $=s=>document.querySelector(s);const blocks=8,lessons=17;let group=7,block=1;
const objectives={
"7-1-1":"Ik kan grote getallen handig optellen en aftrekken.",
"7-1-2":"Ik kan rekenen met geldbedragen en mijn aanpak uitleggen.",
"7-1-3":"Ik kan een contextsom vertalen naar een passende berekening."
};
function exampleLesson(g,b,l){const key=g+"-"+b+"-"+l,goal=objectives[key]||"Ik kan de rekenstrategie van deze les uitleggen en toepassen.";return{name:"Groep "+g+" · Blok "+b+" · Les "+l,pages:[
{background:"bg-plain",objects:[{type:"text",role:"edi-kicker",x:70,y:55,text:"REKENEN · EDI",fontSize:17,color:"#5b5cf0"},{type:"text",role:"edi-title",x:70,y:95,w:850,text:"Lesdoel",fontSize:42,color:"#172033"},{type:"text",role:"edi-card",x:70,y:175,w:820,text:goal,fontSize:30,color:"#172033"},{type:"text",x:70,y:320,w:820,text:"Aan het einde van de les laat ik zien dat ik dit zelfstandig kan.",fontSize:22,color:"#475467"}]},
{background:"bg-dots",objects:[{type:"text",role:"edi-kicker",x:70,y:55,text:"1 · VOORKENNIS",fontSize:17,color:"#5b5cf0"},{type:"text",role:"edi-title",x:70,y:95,w:850,text:"Wat weten we al?",fontSize:42,color:"#172033"},{type:"text",role:"edi-card",x:70,y:185,w:780,text:"1. Welke kennis heb je hiervoor nodig?\n\n2. Los een eenvoudig voorbeeld op.\n\n3. Leg aan je buur uit hoe je dacht.",fontSize:25,color:"#172033"}]},
{background:"bg-grid",objects:[{type:"text",role:"edi-kicker",x:70,y:55,text:"2 · IK DOE",fontSize:17,color:"#5b5cf0"},{type:"text",role:"edi-title",x:70,y:95,w:850,text:"Kijk naar mijn aanpak",fontSize:42,color:"#172033"},{type:"text",role:"edi-card",x:70,y:185,w:780,text:"Voorbeeld\n\nSchrijf hier tijdens de instructie het voorbeeld en model hardop de denkstappen.",fontSize:25,color:"#172033"}]},
{background:"bg-grid",objects:[{type:"text",role:"edi-kicker",x:70,y:55,text:"3 · WIJ DOEN",fontSize:17,color:"#5b5cf0"},{type:"text",role:"edi-title",x:70,y:95,w:850,text:"Nu samen",fontSize:42,color:"#172033"},{type:"text",role:"edi-card",x:70,y:185,w:780,text:"Opgave 1\n\nWat is onze eerste stap?\nWaarom kiezen we die stap?\nWat wordt het antwoord?",fontSize:25,color:"#172033"}]},
{background:"bg-plain",objects:[{type:"text",role:"edi-kicker",x:70,y:55,text:"4 · CONTROLE VAN BEGRIP",fontSize:17,color:"#5b5cf0"},{type:"text",role:"edi-title",x:70,y:95,w:850,text:"Laat het allemaal zien",fontSize:42,color:"#172033"},{type:"text",role:"edi-card",x:70,y:185,w:780,text:"Iedereen denkt. Iedereen antwoordt.\n\nMini-check 1: …\nMini-check 2: …\nLeg je antwoord uit: …",fontSize:25,color:"#172033"}]},
{background:"bg-dots",objects:[{type:"text",role:"edi-kicker",x:70,y:55,text:"5 · JULLIE DOEN",fontSize:17,color:"#5b5cf0"},{type:"text",role:"edi-title",x:70,y:95,w:850,text:"Samen oefenen",fontSize:42,color:"#172033"},{type:"text",role:"edi-card",x:70,y:185,w:780,text:"Werk met je buur.\n\nLos de opdracht allebei op en vergelijk daarna jullie aanpak.",fontSize:25,color:"#172033"},{type:"timer",x:720,y:420,total:180,left:180,mode:"analog",alarm:"chime"}]},
{background:"bg-plain",objects:[{type:"text",role:"edi-kicker",x:70,y:55,text:"6 · JIJ DOET",fontSize:17,color:"#5b5cf0"},{type:"text",role:"edi-title",x:70,y:95,w:850,text:"Zelfstandig aan het werk",fontSize:42,color:"#172033"},{type:"text",role:"edi-card",x:70,y:185,w:780,text:"Je gaat nu zelfstandig verwerken.\n\nKlaar? Controleer je werk en verbeter wat nodig is.",fontSize:25,color:"#172033"},{type:"timer",x:720,y:420,total:600,left:600,mode:"digital",alarm:"bell"}]},
{background:"bg-plain",objects:[{type:"text",role:"edi-kicker",x:70,y:55,text:"7 · AFSLUITING",fontSize:17,color:"#5b5cf0"},{type:"text",role:"edi-title",x:70,y:95,w:850,text:"Kun jij het lesdoel?",fontSize:42,color:"#172033"},{type:"text",role:"edi-card",x:70,y:185,w:780,text:goal+"\n\nExitvraag: laat met één voorbeeld zien dat je het kunt.",fontSize:25,color:"#172033"}]}
]}}
function render(){document.querySelectorAll("[data-group]").forEach(x=>x.classList.toggle("active",+x.dataset.group===group));$("#crumb").textContent="Groep "+group+" · Blok "+block;$("#blocks").innerHTML=Array.from({length:blocks},(_,i)=>'<button data-block="'+(i+1)+'" class="'+(i+1===block?"active":"")+'">Blok '+(i+1)+'</button>').join("");$("#lessons").innerHTML=Array.from({length:lessons},(_,i)=>{let n=i+1,has=!!objectives[group+"-"+block+"-"+n];return '<button class="lesson '+(has?"filled":"")+'" data-lesson="'+n+'"><b>Les '+n+'</b><span>'+(has?"Voorbeeldinhoud":"EDI-basis")+'</span><i>Open bord →</i></button>'}).join("")}
document.addEventListener("click",e=>{let g=e.target.closest("[data-group]");if(g){group=+g.dataset.group;block=1;render();return}let b=e.target.closest("[data-block]");if(b){block=+b.dataset.block;render();return}let l=e.target.closest("[data-lesson]");if(l){let data=exampleLesson(group,block,+l.dataset.lesson);sessionStorage.setItem("atlasBoardTemplate",JSON.stringify(data));location.href="../../board/"}});render()})();