(()=>{"use strict";const $=s=>document.querySelector(s),stage=$("#stage"),ink=$("#ink"),objects=$("#objects"),scroller=$("#scroller");let tool="select",pageIndex=0,selected=null,editing=null,currentId=null,redoStack=[],drawing=null,drag=null;const uid=()=>crypto.randomUUID(),baseH=()=>innerHeight-52-76;
const newPage=()=>({length:1,paper:"#ffffff",overlay:"none",overlayColor:"#d5d9e0",strokes:[],objects:[]});let board={version:3,name:"Nieuw bord",pages:[newPage()]};
const page=()=>board.pages[pageIndex],clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),esc=s=>{const d=document.createElement("div");d.textContent=s||"";return d.innerHTML};
function setTool(t){finishEdit();tool=t;document.querySelectorAll(".mode").forEach(b=>b.classList.toggle("active",b.dataset.tool===t));clearSelection()}
function applyBackground(){let p=page();stage.style.setProperty("--length",p.length);stage.style.setProperty("--paper",p.paper);stage.style.setProperty("--overlay",p.overlayColor);stage.className=p.overlay==="none"?"":"overlay-"+p.overlay;$("#paperColor").value=p.paper;$("#overlay").value=p.overlay;$("#overlayColor").value=p.overlayColor}
function render(){applyBackground();ink.innerHTML="";objects.innerHTML="";page().strokes.forEach(renderStroke);page().objects.forEach(renderObject);$("#pageLabel").textContent=(pageIndex+1)+" / "+board.pages.length;$("#prev").disabled=pageIndex===0;$("#next").disabled=pageIndex===board.pages.length-1;$("#shorten").disabled=page().length<=1;clearSelection();scroller.scrollTop=0}
function pointsAttr(pts){return pts.map(p=>p.x+","+p.y).join(" ")}function renderStroke(s){let el=document.createElementNS("http://www.w3.org/2000/svg","polyline");el.dataset.id=s.id;el.setAttribute("points",pointsAttr(s.points));el.setAttribute("stroke",s.color);el.setAttribute("stroke-width",s.size);el.setAttribute("vector-effect","non-scaling-stroke");el.classList.add("stroke");if(s.kind==="marker"){el.classList.add("marker");el.setAttribute("opacity",".28")}el.style.pointerEvents=tool==="select"?"stroke":"none";ink.append(el)}
function pos(e){let r=stage.getBoundingClientRect();return{x:e.clientX-r.left+scroller.scrollLeft,y:e.clientY-r.top+scroller.scrollTop}}
ink.addEventListener("pointerdown",e=>{if(tool==="select"){let el=e.target.closest(".stroke");if(el){selectStroke(el.dataset.id,e);e.preventDefault()}return}if(!["pen","marker"].includes(tool))return;let p=pos(e),s={id:uid(),kind:tool,color:$("#drawColor").value,size:+$("#drawSize").value*(tool==="marker"?3:1),points:[p]};page().strokes.push(s);drawing=s;redoStack=[];ink.setPointerCapture(e.pointerId);renderStroke(s)});
ink.addEventListener("pointermove",e=>{if(!drawing)return;let p=pos(e),last=drawing.points.at(-1);if(Math.hypot(p.x-last.x,p.y-last.y)<2)return;drawing.points.push(p);let el=ink.querySelector('[data-id="'+drawing.id+'"]');el.setAttribute("points",pointsAttr(drawing.points))});ink.addEventListener("pointerup",()=>drawing=null);ink.addEventListener("pointercancel",()=>drawing=null);
function bounds(s){let xs=s.points.map(p=>p.x),ys=s.points.map(p=>p.y),pad=s.size/2+6;return{x:Math.min(...xs)-pad,y:Math.min(...ys)-pad,w:Math.max(...xs)-Math.min(...xs)+pad*2,h:Math.max(...ys)-Math.min(...ys)+pad*2}}
function selectStroke(id,e){finishEdit();clearSelection();let s=page().strokes.find(x=>x.id===id);if(!s)return;selected={type:"stroke",id};ink.querySelector('[data-id="'+id+'"]').classList.add("selected");let b=bounds(s),box=document.createElement("div");box.className="selected-stroke-box";box.style.cssText="left:"+b.x+"px;top:"+b.y+"px;width:"+b.w+"px;height:"+b.h+"px";objects.append(box);wireStrokeDrag(box,s);showSelection("Penstreek");if(e)e.stopPropagation()}
function wireStrokeDrag(box,s){box.onpointerdown=e=>{let sx=e.clientX,sy=e.clientY,orig=s.points.map(p=>({...p}));box.setPointerCapture(e.pointerId);box.onpointermove=m=>{let dx=m.clientX-sx,dy=m.clientY-sy;s.points=orig.map(p=>({x:p.x+dx,y:p.y+dy}));ink.querySelector('[data-id="'+s.id+'"]').setAttribute("points",pointsAttr(s.points));let b=bounds(s);box.style.left=b.x+"px";box.style.top=b.y+"px"};box.onpointerup=()=>box.onpointermove=null}}
function renderObject(o){let el=document.createElement("div");el.dataset.id=o.id;if(o.type==="text"){el.className="board-object text-object font-"+(o.font||"standard");el.style.cssText="left:"+o.x+"px;top:"+o.y+"px;color:"+o.color+";font-size:"+o.size+"px;width:"+(o.w||"auto")+"px";el.textContent=o.text||"";el.ondblclick=e=>{e.stopPropagation();startEdit(el,o)}}else if(o.type==="note"){el.className="board-object note";el.style.cssText="left:"+o.x+"px;top:"+o.y+"px";el.textContent=o.text||"Notitie";el.ondblclick=()=>startEdit(el,o)}else{el=widgetElement(o)}objects.append(el);wireObject(el,o)}
function wireObject(el,o){el.onpointerdown=e=>{if(tool!=="select"||editing===el||e.target.closest("button"))return;e.stopPropagation();selectObject(el,o);let sx=e.clientX,sy=e.clientY,ox=o.x,oy=o.y;el.setPointerCapture(e.pointerId);el.onpointermove=m=>{o.x=Math.max(0,ox+m.clientX-sx);o.y=Math.max(0,oy+m.clientY-sy);el.style.left=o.x+"px";el.style.top=o.y+"px"};el.onpointerup=()=>el.onpointermove=null}}
function selectObject(el,o){finishEdit();clearSelection();selected={type:"object",id:o.id};el.classList.add("selected");if(o.type==="text"){showTextBar(o);$("#fontFamily").value=o.font||"standard";$("#fontSize").value=o.size;$("#fontColor").value=o.color;$("#fontColor").nextElementSibling.style.background=o.color}else showSelection(o.type==="note"?"Notitie":"Tool")}
function clearSelection(){objects.querySelectorAll(".selected,.selected-stroke-box").forEach(x=>x.classList.remove("selected"));objects.querySelectorAll(".selected-stroke-box").forEach(x=>x.remove());ink.querySelectorAll(".selected").forEach(x=>x.classList.remove("selected"));selected=null;$("#textBar").hidden=true;$("#selectionBar").hidden=true}
function showTextBar(){ $("#selectionBar").hidden=true;$("#textBar").hidden=false}function showSelection(x){$("#textBar").hidden=true;$("#selectionBar").hidden=false;$("#selectionLabel").textContent=x}
function startEdit(el,o){finishEdit();clearSelection();editing=el;el.contentEditable="true";el.focus();let r=document.createRange();r.selectNodeContents(el);r.collapse(false);let s=getSelection();s.removeAllRanges();s.addRange(r);el.onblur=()=>{o.text=el.textContent.trim();el.contentEditable="false";editing=null;if(!o.text){page().objects=page().objects.filter(x=>x.id!==o.id);el.remove()}setTool("select")}}
function finishEdit(){if(editing){editing.blur();editing=null}}
stage.addEventListener("pointerdown",e=>{if(e.target!==stage&&e.target!==objects)return;if(tool==="text"){let p=pos(e),o={id:uid(),type:"text",x:p.x,y:p.y,text:"",font:"standard",size:32,color:$("#drawColor").value};page().objects.push(o);renderObject(o);startEdit(objects.querySelector('[data-id="'+o.id+'"]'),o);return}if(tool==="select")clearSelection()});
function widgetElement(o){let el=document.createElement("div");el.className="board-object widget";el.style.cssText="left:"+o.x+"px;top:"+o.y+"px";let body="";if(o.type==="timer")body='<div class="widget-head">TIMER</div><div class="widget-body"><div class="timer-display">05:00</div><button data-act="timer">Start</button><button data-act="reset">↺</button></div>';if(o.type==="clock")body='<div class="widget-head">KLOK</div><div class="widget-body"><div class="clock-display">--:--</div></div>';if(o.type==="traffic")body='<div class="widget-head">STOPLICHT</div><div class="widget-body traffic-lights"><button class="light red" data-light="0"></button><button class="light amber" data-light="1"></button><button class="light green active" data-light="2"></button></div>';if(o.type==="dice")body='<div class="widget-head">DOBBELSTEEN</div><div class="widget-body"><div class="die">⚄</div><button data-act="roll">Gooi</button></div>';if(o.type==="counter")body='<div class="widget-head">TELLER</div><div class="widget-body"><div class="counter-value">'+(o.value||0)+'</div><button data-act="minus">−</button><button data-act="plus">＋</button></div>';
if(o.type==="stopwatch")body='<div class="widget-head">STOPWATCH</div><div class="widget-body"><div class="stopwatch-display">00:00.0</div><button data-act="sw">Start</button><button data-act="swreset">↺</button></div>';
if(o.type==="random")body='<div class="widget-head">WILLEKEURIGE NAAM</div><div class="widget-body"><textarea class="widget-input" placeholder="Eén naam per regel"></textarea><div class="names-result">Wie wordt het?</div><button data-act="pick">Kies naam</button></div>';
if(o.type==="groups")body='<div class="widget-head">GROEPJESMAKER</div><div class="widget-body"><textarea class="widget-input" placeholder="Eén naam per regel"></textarea><input class="widget-input group-size" type="number" min="2" value="3" title="Groepsgrootte"><button data-act="groups">Maak groepjes</button><div class="groups-result"></div></div>';
if(o.type==="wheel")body='<div class="widget-head">DRAAIWIEL</div><div class="widget-body"><textarea class="widget-input" placeholder="Eén keuze per regel"></textarea><div class="wheel-disc"></div><div class="wheel-result"></div><button data-act="spin">Draai</button></div>';
if(o.type==="qr")body='<div class="widget-head">QR / LINK</div><div class="widget-body"><input class="widget-input" placeholder="https://…"><div class="qrbox">Vul een link in</div><button data-act="qr">Toon link</button></div>';
if(o.type==="symbol")body='<div class="widget-head">INSTRUCTIE</div><div class="widget-body"><div class="symbol-face">👀</div><div class="symbol-label">Kijk</div><button data-act="symbol">Volgende</button></div>';
if(o.type==="noise")body='<div class="widget-head">GELUIDSNIVEAU</div><div class="widget-body"><div class="noise-label">Rustig</div><div class="noise-meter"><div class="noise-fill"></div></div><button data-act="noise">Microfoon starten</button><div class="mini">Vraagt toestemming van de browser</div></div>';
el.innerHTML=body;wireWidget(el,o);return el}
const dice=["⚀","⚁","⚂","⚃","⚄","⚅"];function wireWidget(el,o){if(o.type==="clock"){let tick=()=>{let d=new Date;el.querySelector(".clock-display").textContent=d.toLocaleTimeString("nl-NL",{hour:"2-digit",minute:"2-digit"})};tick();setInterval(()=>document.body.contains(el)&&tick(),10000)}if(o.type==="timer"){o.total=o.total||300;o.left=o.left??o.total;o.running=false;let paint=()=>el.querySelector(".timer-display").textContent=String(Math.floor(o.left/60)).padStart(2,"0")+":"+String(o.left%60).padStart(2,"0"),int;paint();el.querySelector('[data-act="timer"]').onclick=e=>{e.stopPropagation();if(int){clearInterval(int);int=null;e.target.textContent="Start"}else{e.target.textContent="Pauze";int=setInterval(()=>{o.left=Math.max(0,o.left-1);paint();if(!o.left){clearInterval(int);int=null;e.target.textContent="Start"}},1000)}};el.querySelector('[data-act="reset"]').onclick=e=>{e.stopPropagation();clearInterval(int);int=null;o.left=o.total;paint()}}if(o.type==="traffic")el.querySelectorAll("[data-light]").forEach(b=>b.onclick=e=>{e.stopPropagation();el.querySelectorAll(".light").forEach(x=>x.classList.remove("active"));b.classList.add("active");o.active=+b.dataset.light});if(o.type==="dice")el.querySelector('[data-act="roll"]').onclick=e=>{e.stopPropagation();let n=Math.floor(Math.random()*6);o.value=n+1;el.querySelector(".die").textContent=dice[n]};if(o.type==="counter"){let paint=()=>el.querySelector(".counter-value").textContent=o.value||0;el.querySelector('[data-act="plus"]').onclick=e=>{e.stopPropagation();o.value=(o.value||0)+1;paint()};el.querySelector('[data-act="minus"]').onclick=e=>{e.stopPropagation();o.value=(o.value||0)-1;paint()}}
if(o.type==="stopwatch"){let ms=o.ms||0,startAt=0,int=null,d=el.querySelector(".stopwatch-display"),paint=()=>{let t=ms+(int?performance.now()-startAt:0),m=Math.floor(t/60000),sec=Math.floor(t%60000/1000),ds=Math.floor(t%1000/100);d.textContent=String(m).padStart(2,"0")+":"+String(sec).padStart(2,"0")+"."+ds};paint();el.querySelector('[data-act="sw"]').onclick=e=>{e.stopPropagation();if(int){ms+=performance.now()-startAt;o.ms=ms;clearInterval(int);int=null;e.target.textContent="Start"}else{startAt=performance.now();int=setInterval(paint,100);e.target.textContent="Pauze"}};el.querySelector('[data-act="swreset"]').onclick=e=>{e.stopPropagation();clearInterval(int);int=null;ms=o.ms=0;paint()}}
if(o.type==="random"){let ta=el.querySelector("textarea"),res=el.querySelector(".names-result");ta.value=(o.names||[]).join("\n");ta.oninput=()=>o.names=ta.value.split(/\n/).map(x=>x.trim()).filter(Boolean);el.querySelector('[data-act="pick"]').onclick=e=>{e.stopPropagation();let a=o.names||[];res.textContent=a.length?a[Math.floor(Math.random()*a.length)]:"Voeg eerst namen toe"}}
if(o.type==="groups"){let ta=el.querySelector("textarea"),sz=el.querySelector(".group-size"),res=el.querySelector(".groups-result");ta.value=(o.names||[]).join("\n");ta.oninput=()=>o.names=ta.value.split(/\n/).map(x=>x.trim()).filter(Boolean);el.querySelector('[data-act="groups"]').onclick=e=>{e.stopPropagation();let a=[...(o.names||[])].sort(()=>Math.random()-.5),n=Math.max(2,+sz.value||3),gs=[];for(let i=0;i<a.length;i+=n)gs.push(a.slice(i,i+n));res.innerHTML=gs.length?gs.map((g,i)=>"<b>Groep "+(i+1)+":</b> "+esc(g.join(", "))).join("<br>"):"Voeg eerst namen toe"}}
if(o.type==="wheel"){let ta=el.querySelector("textarea"),disc=el.querySelector(".wheel-disc"),res=el.querySelector(".wheel-result"),turn=0;ta.value=(o.items||[]).join("\n");ta.oninput=()=>o.items=ta.value.split(/\n/).map(x=>x.trim()).filter(Boolean);el.querySelector('[data-act="spin"]').onclick=e=>{e.stopPropagation();let a=o.items||[];if(!a.length){res.textContent="Voeg keuzes toe";return}turn+=720+Math.floor(Math.random()*720);disc.style.transform="rotate("+turn+"deg)";let pick=a[Math.floor(Math.random()*a.length)];setTimeout(()=>res.textContent=pick,1100)}}
if(o.type==="qr"){let input=el.querySelector("input"),box=el.querySelector(".qrbox");input.value=o.url||"";el.querySelector('[data-act="qr"]').onclick=e=>{e.stopPropagation();o.url=input.value.trim();box.textContent=o.url||"Vul een link in"}}
if(o.type==="symbol"){let vals=[["👀","Kijk"],["👂","Luister"],["🤫","Stil werken"],["💬","Overleggen"],["✋","Hand opsteken"],["✏️","Schrijven"]],i=o.symbol||0,face=el.querySelector(".symbol-face"),lab=el.querySelector(".symbol-label"),paint=()=>{face.textContent=vals[i][0];lab.textContent=vals[i][1];o.symbol=i};paint();el.querySelector('[data-act="symbol"]').onclick=e=>{e.stopPropagation();i=(i+1)%vals.length;paint()}}
if(o.type==="noise"){let btn=el.querySelector('[data-act="noise"]'),fill=el.querySelector(".noise-fill"),lab=el.querySelector(".noise-label"),ctx,stream,raf;btn.onclick=async e=>{e.stopPropagation();if(stream){stream.getTracks().forEach(t=>t.stop());cancelAnimationFrame(raf);stream=null;btn.textContent="Microfoon starten";return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});ctx=new(window.AudioContext||window.webkitAudioContext)();let src=ctx.createMediaStreamSource(stream),an=ctx.createAnalyser(),data=new Uint8Array(an.fftSize);src.connect(an);btn.textContent="Stop";let tick=()=>{an.getByteTimeDomainData(data);let sum=0;for(let v of data){let x=(v-128)/128;sum+=x*x}let rms=Math.sqrt(sum/data.length),pct=Math.min(100,Math.max(3,rms*420));fill.style.width=pct+"%";lab.textContent=pct<28?"Rustig":pct<60?"Let op":"Te luid";raf=requestAnimationFrame(tick)};tick()}catch{lab.textContent="Geen microfoontoegang"}}}}
function addObject(type){let o={id:uid(),type,x:90+page().objects.length*12,y:90+scroller.scrollTop};if(type==="note")o.text="Notitie";if(type==="counter")o.value=0;if(["random","groups"].includes(type))o.names=[];if(type==="wheel")o.items=[];page().objects.push(o);renderObject(o);closePanels()}
function removeSelected(){if(!selected)return;if(selected.type==="stroke")page().strokes=page().strokes.filter(x=>x.id!==selected.id);else page().objects=page().objects.filter(x=>x.id!==selected.id);render()}
function duplicateSelected(){if(!selected)return;let arr=selected.type==="stroke"?page().strokes:page().objects,o=arr.find(x=>x.id===selected.id);if(!o)return;let c=structuredClone(o);c.id=uid();if(c.points)c.points=c.points.map(p=>({x:p.x+25,y:p.y+25}));else{c.x+=25;c.y+=25}arr.push(c);render()}
$("#delete").onclick=$("#delete2").onclick=removeSelected;$("#duplicate").onclick=$("#duplicate2").onclick=duplicateSelected;document.addEventListener("keydown",e=>{if((e.key==="Delete"||e.key==="Backspace")&&selected&&!editing){e.preventDefault();removeSelected()}});
document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$("#drawColor").oninput=e=>e.target.nextElementSibling.style.background=e.target.value;
$("#fontFamily").onchange=e=>updateText(o=>o.font=e.target.value);$("#fontSize").oninput=e=>updateText(o=>o.size=clamp(+e.target.value,12,160));$("#fontColor").oninput=e=>{e.target.nextElementSibling.style.background=e.target.value;updateText(o=>o.color=e.target.value)};function updateText(fn){if(!selected||selected.type!=="object")return;let o=page().objects.find(x=>x.id===selected.id);if(!o||o.type!=="text")return;fn(o);let el=objects.querySelector('[data-id="'+o.id+'"]');el.className="board-object text-object selected font-"+o.font;el.style.fontSize=o.size+"px";el.style.color=o.color}
$("#extend").onclick=()=>{page().length++;applyBackground();$("#shorten").disabled=false};$("#shorten").onclick=()=>{if(page().length<=1)return;let limit=(page().length-1)*baseH(),occupied=page().objects.some(o=>o.y>limit-100)||page().strokes.some(s=>s.points.some(p=>p.y>limit-50));if(occupied)return alert("Onderaan staan nog objecten. Verplaats of verwijder die eerst.");page().length--;applyBackground()};
$("#prev").onclick=()=>{if(pageIndex){pageIndex--;render()}};$("#next").onclick=()=>{if(pageIndex<board.pages.length-1){pageIndex++;render()}};$("#addPage").onclick=()=>{board.pages.push(newPage());pageIndex=board.pages.length-1;render()};$("#clonePage").onclick=()=>{let c=structuredClone(page());c.strokes.forEach(s=>s.id=uid());c.objects.forEach(o=>o.id=uid());board.pages.splice(pageIndex+1,0,c);pageIndex++;render()};
$("#undo").onclick=()=>{let p=page(),item=p.strokes.pop();if(item){redoStack.push(item);render()}};$("#redo").onclick=()=>{let x=redoStack.pop();if(x){page().strokes.push(x);render()}};
function closePanels(){document.querySelectorAll(".panel").forEach(x=>x.hidden=true)}$("#toolsButton").onclick=()=>{$("#toolsPanel").hidden=!$("#toolsPanel").hidden;$("#backgroundPanel").hidden=true};$("#backgroundButton").onclick=()=>{$("#backgroundPanel").hidden=!$("#backgroundPanel").hidden;$("#toolsPanel").hidden=true};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=closePanels);$("#toolsPanel").onclick=e=>{let b=e.target.closest("[data-add]");if(b)addObject(b.dataset.add)};$("#paperColor").oninput=e=>{page().paper=e.target.value;applyBackground()};$("#overlayColor").oninput=e=>{page().overlayColor=e.target.value;applyBackground()};$("#overlay").onchange=e=>{page().overlay=e.target.value;applyBackground()};
$("#fullscreen").onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
const DB="atlas-board-db";function db(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore("boards",{keyPath:"id"});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}async function all(){let d=await db(),r=d.transaction("boards").objectStore("boards").getAll();return new Promise(ok=>r.onsuccess=()=>ok(r.result))}async function put(x){let d=await db(),t=d.transaction("boards","readwrite");t.objectStore("boards").put(x);return new Promise(ok=>t.oncomplete=ok)}async function del(id){let d=await db(),t=d.transaction("boards","readwrite");t.objectStore("boards").delete(id);return new Promise(ok=>t.oncomplete=ok)}
$("#saveBoard").onclick=async()=>{let name=prompt("Naam van dit bord:",board.name==="Nieuw bord"?"Mijn bord":board.name);if(!name)return;board.name=name;$("#boardName").textContent=name;let b={...structuredClone(board),id:currentId||uid(),updated:Date.now()};currentId=b.id;await put(b);$("#saveBoard").textContent="Opgeslagen ✓";setTimeout(()=>$("#saveBoard").textContent="Opslaan",1000)};
const dlg=$("#boardsDialog"),list=$("#boardsList");$("#openBoard").onclick=async()=>{let bs=(await all()).sort((a,b)=>b.updated-a.updated);list.innerHTML=bs.length?bs.map(b=>'<div class="saved" data-id="'+b.id+'"><span><b>'+esc(b.name)+'</b><small>'+(b.pages?.length||1)+' pagina(s)</small></span><button data-open>Open</button><button data-del>🗑</button></div>').join(""):"Nog geen opgeslagen borden.";dlg.showModal()};$("#closeBoards").onclick=()=>dlg.close();list.onclick=async e=>{let r=e.target.closest(".saved");if(!r)return;if(e.target.closest("[data-del]")){await del(r.dataset.id);r.remove();return}if(e.target.closest("[data-open]")){let b=(await all()).find(x=>x.id===r.dataset.id);if(!b)return;if(b.version!==3)return alert("Dit bord is uit de oude Board-versie. Maak hiervoor voorlopig een nieuw bord.");board=b;currentId=b.id;pageIndex=0;$("#boardName").textContent=b.name;render();dlg.close()}};
function loadTemplate(){let raw=sessionStorage.getItem("atlasBoardTemplate");if(!raw)return false;sessionStorage.removeItem("atlasBoardTemplate");try{let t=JSON.parse(raw);board={version:3,name:t.name||"EDI-les",pages:(t.pages||[]).map(p=>({length:p.height||1,paper:p.background==="bg-dark"?"#202733":"#ffffff",overlay:p.background==="bg-grid"?"grid":p.background==="bg-dots"?"dots":p.background==="bg-lines"?"lines":"none",overlayColor:"#d5d9e0",strokes:[],objects:(p.objects||[]).map(o=>({id:o.id||uid(),type:o.type,x:o.x||70,y:o.y||70,text:o.text||"",font:"standard",size:o.fontSize||32,color:o.color||"#172033",w:o.w,total:o.total,left:o.left,mode:o.mode,alarm:o.alarm}))}))};$("#boardName").textContent=board.name;return true}catch{return false}}
loadTemplate();render();})();